version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: recs
      POSTGRES_PASSWORD: recs_pass
      POSTGRES_DB: recs_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
